name: Trigger auto deployment for fr24-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fr24-bot-AutoDeployTrigger-b16a417d-750d-43dc-b383-9ee4af4d8b54.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FR24BOT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FR24BOT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FR24BOT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fr24acr436683029.azurecr.io
          registryUsername: ${{ secrets.FR24BOT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FR24BOT_REGISTRY_PASSWORD }}
          containerAppName: fr24-bot
          resourceGroup: fr24-rg
          imageToBuild: fr24acr436683029.azurecr.io/fr24-bot:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


